#!/bin/bash
table_name=$1
col_name=$3
col_type=$4
db=`cat ./system/session | cut -d : -f2`

if [[ ! $db ]]; then
	echo -6 #use database first
	exit
fi

if [[ ! `ls -1 ./databases/$db |egrep ^$table_name ` ]]; then
	echo -1
	exit
fi

if [[ $2 != "column" || ! $col_name || ! $col_type ]]; then
	echo -4
	exit
fi

if [[ `egrep "^${col_name}:" ./metadata/$db/$table_name` ]]
	then
		echo -16
		exit
fi

if [[ `egrep "pk" tmp/table` && `head -1 ./metadata/$db/$table_name | cut -d ":" -f3` == 1  ]]; then
	echo -14
	exit
fi

if [[ `egrep "a_i" tmp/table` && ! `egrep "pk" tmp/table` ]]; then
	echo -14
	exit
fi

awk -v f_name=$col_name -v f_type=$col_type 'BEGIN{
	OFS = ":"
	f_pk = 0 
	f_null = 0 
	f_a_i = 0 
	f_unique = 0
}{
	for(i = 0 ; i<NF ; i++){
		if ($i == "pk")
			f_pk = 1
		else if ($i == "null")
			f_null = 1
		else if ($i == "a_i")
			f_a_i = 1
		else if ($i == "unique")
			f_unique = 1
		}
	

	print f_name , f_type , f_pk , f_unique , f_null , f_a_i
}' tmp/table >> metadata/$db/$table_name
cat metadata/$db/$table_name > tmp/table_im
egrep "[a-zA-Z0-9_-]+:[a-z]*:1:.*" tmp/table_im > metadata/$db/$table_name
sed -E "/[a-zA-Z0-9_-]+:[a-z]*:1:.*/d" tmp/table_im >> metadata/$db/$table_name
rm ./tmp/table_im 
rm ./tmp/table







