#!/bin/bash
table_name=$1
col_name=$3

db=`cat ./system/session | cut -d : -f2`

if [[ ! $db ]]; then
	echo -6 #use database first
	exit
fi

if [[ ! `ls -1 ./databases/$db |egrep ^$table_name ` ]]; then
	echo -1
	exit
fi

if [[ $2 != "column" || ! $col_name ]]; then
	echo -4
	exit
fi

sed -i "/^${col_name}:/d" metadata/$db/$table_name








