#!/bin/bash
table_name=$1
db=`cat ./system/session | cut -d ":" -f2`
if [[ ! $db ]]; then
	echo -6 #use database first
	exit
fi

if [[ ! `ls -1 ./databases/$db | egrep ^$table_name` ]]; then
	echo -1
	exit
fi

cat ./databases/company/employee > ./tmp/$table_name

while IFS='' read -r line || [[ -n "$line" ]]; do

	if [[ `echo $line | egrep "and"`  ]]; then
		line=`echo $line | cut -d " " -f2`
		key=`echo $line | cut -d "=" -f1`
		val=`echo $line | cut -d "=" -f2`
		num=`awk -v col_name=$key 'BEGIN{ FS = ":" }{ if( $1 == col_name ){ print NR } }' ./metadata/${db}/${table_name}`
		awk -v f=$num -v v=$val  'BEGIN{ FS = ":" ; OFS = ":" }{ if( $f==v ) print $0 }' ./tmp/$table_name > ./tmp/tmp_res
		cat ./tmp/tmp_res > ./tmp/$table_name
	fi

	if [[ `echo $line | egrep "rx"`  ]]; then
		line=`echo $line | cut -d " " -f2`
		key=`echo $line | cut -d "~" -f1`
		val=`echo $line | cut -d "~" -f2`
		num=`awk -v col_name=$key 'BEGIN{ FS = ":" }{ if( $1 == col_name ){ print NR } }' ./metadata/${db}/${table_name}`
		awk -v f=$num -v v=$val  'BEGIN{ FS = ":" ; OFS = ":" }{ if( match( $f , v) ) print $0 }' ./tmp/$table_name > ./tmp/tmp_res
		cat ./tmp/tmp_res > ./tmp/$table_name
	fi
done < ./tmp/table


pks=`cat ./tmp/$table_name | cut -d":" -f1 | tr "\n" "," | head -c -1`
awk -v pks=$pks 'BEGIN{ FS = ":" ;  OFS = ":" ; split ( pks , pks_arr , /,/);} { is_print = 1 ; for ( j in pks_arr ) if ( $1 == pks_arr[j] ) is_print = 0 ; if ( is_print ) print $0  }' ./databases/$db/$table_name > ./tmp/$table_name
cat ./tmp/$table_name > ./databases/$db/$table_name



