#!/bin/bash
table_name=$1
field_name=$2
db=`cat ./system/session | cut -d : -f2`
if [[ ! $db ]]; then
	echo -6 #use database first
	exit
fi

if [[ ! `ls -1 ./databases/$db | egrep ^$table_name` ]]; then
	echo -1
	exit
fi

cat ./databases/company/employee > ./tmp/$table_name

while IFS='' read -r line || [[ -n "$line" ]]; do

	if [[ `echo $line | egrep "and"`  ]]; then
		line=`echo $line | cut -d " " -f2`
		key=`echo $line | cut -d "=" -f1`
		val=`echo $line | cut -d "=" -f2`
		num=`awk -v col_name=$key 'BEGIN{ FS = ":" }{ if( $1 == col_name ){ print NR } }' ./metadata/${db}/${table_name}`
		awk -v f=$num -v v=$val  'BEGIN{ FS = ":" ; OFS = ":" }{ if( $f==v ) print $0 }' ./tmp/$table_name > ./tmp/tmp_res
		cat ./tmp/tmp_res > ./tmp/$table_name
	fi

	if [[ `echo $line | egrep "rx"`  ]]; then
		line=`echo $line | cut -d " " -f2`
		key=`echo $line | cut -d "~" -f1`
		val=`echo $line | cut -d "~" -f2`
		num=`awk -v col_name=$key 'BEGIN{ FS = ":" }{ if( $1 == col_name ){ print NR } }' ./metadata/${db}/${table_name}`
		awk -v f=$num -v v=$val  'BEGIN{ FS = ":" ; OFS = ":" }{ if( match( $f , v) ) print $0 }' ./tmp/$table_name > ./tmp/tmp_res
		cat ./tmp/tmp_res > ./tmp/$table_name
	fi
done < ./tmp/table

echo $field_name | tr "," "\n" > ./tmp/update_$table_name

declare -A data
while IFS='' read -r line || [[ -n "$line" ]]; do
	key=`echo $line | cut -d "=" -f1`
	val=`echo $line | cut -d "=" -f2`
	if [[ ! $val ]]; then
		echo -8
		exit
	fi
	data[$key]=$val
done < ./tmp/update_$table_name

keys=""
vals=""
for key in "${!data[@]}";do
	keys="${keys}${key},"
	vals="${vals}${data[$key]},"
done
keys=`echo -n $keys | head -c -1`
vals=`echo -n $vals | head -c -1`


declare -A col
declare -A type_of
declare -A is_pk
declare -A is_unique
declare -A is_null
declare -A is_ai

while IFS='' read -r line || [[ -n "$line" ]]; do
	key=`echo $line | cut -d ":" -f1`
	col[$key]=0
	type_of[$key]=`echo $line | cut -d ":" -f2`
	is_pk[$key]=`echo $line | cut -d ":" -f3`
	is_unique[$key]=`echo $line | cut -d ":" -f4`
	is_null[$key]=`echo $line | cut -d ":" -f5`
	is_ai[$key]=`echo $line | cut -d ":" -f6`
done < metadata/$db/$table_name

for K in "${!data[@]}";do


	case ${type_of[$K]} in 
		int)
			if [[ ${data[$K]} =~ ^[0-9]+$ ]]; then 
				pass=1
			else
				echo -9
				exit
			fi 
		;;
		varchar)
			##
		;;
		*)
			echo -1
			exit
		;;
	esac
	if [[ ${data[$K]} && ${is_pk[$K]} == "1" ]]; then
		if  [[ `egrep ^${data[$K]}: ./databases/$db/$table_name` ]]
			then
			 echo -10
			 exit
		fi
fi

done

pks=`cat ./tmp/$table_name | cut -d":" -f1 | tr "\n" "," | head -c -1`
num=`awk -v col_names=$keys 'BEGIN{ FS = ":" ; split ( col_names , col_arr , /,/); } {  flag = 0 ;  for ( i in col_arr ) { if( col_arr[i] == $1 ) flag = 1 ; } if( flag ){ printf("%s,", NR ) } }' ./metadata/$db/$table_name | head -c -1`
awk -v nums=$num -v vals=$vals -v pks=$pks 'BEGIN{ FS = ":" ;  OFS = ":" ;  split ( nums , num_arr , /,/); split ( vals , val_arr , /,/); split ( pks , pks_arr , /,/);} { for ( i in num_arr ) { for ( j in pks_arr ) if ( $1 == pks_arr[j] ) gsub( $num_arr[i] , val_arr[i] , $num_arr[i]) ; } print $0 }' ./databases/$db/$table_name > ./tmp/$table_name
cat ./tmp/$table_name > ./databases/$db/$table_name



