#!/bin/bash
user=$1
password=$2
pass=`echo -n $2| md5sum | awk '{ print $1 }'`
lastuser=`tail -1 ../system/passwd`
lastid=`echo $lastuser | cut -d: -f1`
new_id=$(( $lastid + 1 ))
db_user=`egrep :$user: ../system/passwd` 
if [ $db_user ]
	then
	echo -3 #user already registered 
else
	echo "$new_id:$user:$pass" >> ../system/passwd
fi 