 0 #wrong password
-1 #not found
-2 #confirmation error
-3 #already registered 
-4 #command doesn't exist
-5 #not loged in
-6 #use database first
-7 #repeated entry
-8 #non-nullable entry missing
-9 #type not matching
-10 #repeated primary key value 
-11 #wrong column name
-12 #this is reserved word
-13 #too many args
-14 #command denied 
-15 #wrong value