#!/bin/bash
table_name=$1
db=`cat ./system/session | cut -d : -f2`
if [[ ! $db ]]; then
	echo -6 #use database first
	exit
fi
is_table=`ls -1 ./databases/$db |egrep ^$table_name ` 
if [[ ! $is_table ]]; then
	echo -1
	exit
fi
echo -n "" > ./tmp/table_im
restrictions=`cat metadata/$db/$table_name`
echo $restrictions
current_field=0
declare -A data
while IFS='' read -r line || [[ -n "$line" ]]; do
	key=`echo $line | cut -d "=" -f1`
	val=`echo $line | cut -d "=" -f2`
	$data[$key]=$val
    echo "Text read from file: ${data[key]}"
done < tmp/table
# awk -v restrictions="$restrictions" '
# function is_type_matching(input,type) {
#     if (type == "int"){
#     	regex="/[0-9]+/"
#     	return match($input,$regex)
#     }
#     else if (type == "varchar"){
#     	regex="/[a-zA-Z0-9._-]+/"
#     	return match($input,$regex)
#     }
#     else
#         return 0

# }
# BEGIN {
# 	OFS = ":"
# 	FS = "="
	
# } 
# {
# 	print $xyz
# }
# ' ./tmp/table >> ./tmp/table_im
