#!/bin/bash
user=$1
pass=`echo -n $2| md5sum | awk '{ print $1 }'`
db_user=`egrep :$user: ../system/passwd` 
if [ $db_user ]
	then
	username=`echo $db_user | cut -d: -f2`
	passwrd=`echo $db_user | cut -d: -f3`
		if [ $passwrd  == $pass ]
			then
			USER_ID=`echo $db_user | cut -d: -f1`
			echo $USER_ID
		else
			echo 0 #wrong password
		fi
	else
		echo -1 #not found 
fi