#!/bin/bash
user=$1
db_user=`egrep :$user: ./system/passwd`
if [ $db_user ]
	then
	username=`echo $db_user | cut -d: -f2`
	user_id=`echo $db_user | cut -d: -f1`
	read -s -p 'Enter old password: ' old
	echo
	old_pass=`echo -n $old| md5sum | awk '{ print $1 }'`
	passwrd=`echo $db_user | cut -d: -f3`
	if [ $passwrd  == $old_pass ]
		then
		read -s -p 'Enter new password: ' new_pass
		echo
		read -s -p 'Confirm new password: ' confirm_pass
		echo
		if [ $new_pass  == $confirm_pass ]
			then
			pass=`echo -n $new_pass| md5sum | awk '{ print $1 }'`
			sed -i "s/^${user_id}.*/$user_id:${user}:$pass/" ./system/passwd
			# sed 's/$old_pass/p' ../system/passwd
		else
			echo -2 #confirmation error	
		fi
	else
		echo 0 #wrong password
	fi
else
	echo -1 #not found	
fi		