#!/bin/bash
user=$1


db_user=`egrep :$user: ../system/passwd` 
if [ $db_user ]
	then
	read -p "enter the password :  "  password
	pass=`echo -n $password| md5sum | awk '{ print $1 }'`
	passwrd=`echo $db_user | cut -d: -f3`
		if [ $passwrd  == $pass ]
			then
			user_id=`echo $db_user | cut -d: -f1`		
			sed -i "/^${user_id}.*/d" ../system/passwd
		else
			echo 0 #wrong password	
		fi
else
	echo -1 #not found
fi